### ISSUE TITLE
Is it possible to build pytorch 1.12 with cuda 10.1 in linux through this repo?

### ISSUE THREAD

**Issue by wang-jinbo** [llv22/pytorch-macOS-cuda#3]
Just asking: Is it possible to build pytorch 1.12 with cuda 10.1 in linux through this repo?
If not, could you please inform what modifications is needed, thanks.

**Comment by llv22** [comment]
@Wongboo It supports. please use https://github.com/llv22/pytorch-macOS-cuda/tree/v1.12.0-tensorpipe-fixed and change tensorpiple repo to https://github.com/llv22/tensorpipe-macos-cuda. I wrote several lines of code for macOS to dynamically load library

**Comment by llv22** [comment]
@Wongboo don't worry, I'm now using torch 1.12 on my macOS for my research work. If everything is wrong, I will fix it ^-^

**Comment by wang-jinbo** [comment]
Really appreciated for your help!
I try to build pytorch with following diffences:
- On Linux, CentOS 7 with conda-forge's GCC 8.5.0, cuda 10.1, cudnn 8.0.5
- modify hard-coded conda path to my own conda path in CMakeLists.txt
- modify hard-coded .dylib to .so for linux
When I compile, it seems to get error like:
- `CUPTI_ERROR_LEGACY_PROFILER_NOT_SUPPORTED` not found in 'pytorch-macOS-cuda/third_party/kineto/libkineto/src/CuptiEventApi.cpp', so I change to `CUPTI_ERROR_UM_PROFILER_NOT_SUPPORTED` which solves problem.
-  A lot of cudnn errors in building `caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cudnn/Conv_v8.cpp.o`, such as 
```
pytorch-macOS-cuda/cmake/../third_party/cudnn_frontend/include/cudnn_frontend_utils.h:93:14: error: 'CUDNN_DATA_INT64' was not declared in this scope
pytorch-macOS-cuda/cmake/../third_party/cudnn_frontend/include/cudnn_frontend_PointWiseDesc.h:87:18: error: 'CUDNN_POINTWISE_RELU_BWD' was not declared in this scope
```
Which I cannot handle at all, problems seem to be similar with (https://discuss.pytorch.org/t/ninja-build-stopped-subcommand-failed-when-installing-pytorch-from-source/116624/11), have you got similar error before or have you got any clue? Really wanna hear your suggestions!

**Comment by llv22** [comment]
@Wongboo sorry, my repo is just built for macOS 10.13.6, not for linux. The original purpose is to make Nvidia GPU 1080 box available for my macOS 10.13.6 by eGPU

**Comment by wang-jinbo** [comment]
OK, thanks for reply

**Comment by llv22** [comment]
@Wongboo I think you may want to build torch on linux via cuda 10.1. Is it the case? I think that is the case. And on macOS there is no cuda issue. I mean, in torch there exists none of explicitly cuda c++ dependency. Good news? ^-^ Please try. 

--- a/cmake/public/cuda.cmake
+++ b/cmake/public/cuda.cmake
@@ -45,8 +45,8 @@ set(CMAKE_CUDA_STANDARD_REQUIRED ON)
 message(STATUS "Caffe2: CUDA detected: " ${CUDA_VERSION})
 message(STATUS "Caffe2: CUDA nvcc is: " ${CUDA_NVCC_EXECUTABLE})
 message(STATUS "Caffe2: CUDA toolkit directory: " ${CUDA_TOOLKIT_ROOT_DIR})
-if(CUDA_VERSION VERSION_LESS 10.2)
-  message(FATAL_ERROR "PyTorch requires CUDA 10.2 or above.")
+if(CUDA_VERSION VERSION_LESS 10.1)
+  message(FATAL_ERROR "PyTorch requires CUDA 10.1 or above.")
 endif()

**Comment by llv22** [comment]
@Wongboo just do it based on the standard torch 1.12.0 branch from https://github.com/pytorch/pytorch/tree/v1.12.0. ^-^

**Comment by wang-jinbo** [comment]
Thanks for reply, I'm trying to compile, but seems to be very difficult, may I ask what compiler do you use in MacOS to compile pytorch?

**Comment by llv22** [comment]
@llv22 clang embeded in Xcode 

(base) Orlando:~ llv23$ clang --version
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by llv22** [comment]
As I answered the question, then I closed it
