### ISSUE TITLE
pytorch 2.0.0 jit compile fails

### ISSUE THREAD

**Issue by nagra00** [llv22/pytorch-macOS-cuda#4]
### 🐛 Describe the bug

I have noticed that nvcc throughs an error on jit compile.

The reason of the problem is in jit_utils.cpp

jit_utils.cpp:1550  contains "--std=c++17“ replacing it by  "--std=c++14" seems to fix it.

I have a question regarding CUDA memory. I have a headless TitanX but only 8-9GB of memory can be used by CUDA. Seems there is memory reserved. I can’t find any information if and how it is possible to make all memory available to CUDA for a headless GPU. Any ideas?

### Versions

2.0.0

**Comment by llv22** [comment]
You can use cuda-smi on Mac to check availab cuda memory
https://github.com/al42and/cuda-smi

**Comment by nagra00** [comment]
cuda-smi reports 12GB free but when i try to allocate for example 10GB, CUDA reports "out of memory".  It seems that MacOS prevents CUDA from using all available memory. Most likely MacOS reserves memory for frame buffer use which makes no sense for a headless GPU. I wonder if there is a setting somewhere to change this.

**Comment by llv22** [comment]
@nagra00 cuda-smi doesn't have very fine-grained memory statistics control. Check https://github.com/al42and/cuda-smi/blob/master/cuda-smi.cpp#Line57.

void getMemoryUsageCUDA(int deviceId, size_t &memUsed, size_t &memTotal) {
    size_t memFree;
    CUDA_CALL(cudaSetDevice, deviceId);
    CUDA_CALL(cudaMemGetInfo, &memFree, &memTotal);
    memUsed = memTotal - memFree;
    memUsed = memUsed / 1024 / 1024;
    memTotal = memTotal / 1024 / 1024;
}

If you check in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__MEMORY.html#group__CUDART__MEMORY_1g376b97f5ab20321ca46f7cfa9511b978

Returns in *total the total amount of memory available to the the current context. Returns in *free the amount of memory on the device that is free according to the OS. **CUDA is not guaranteed to be able to allocate all of the memory that the OS reports as free. In a multi-tenet situation, free estimate returned is prone to race condition where a new allocation/free done by a different process or a different thread in the same process between the time when free memory was estimated and reported, will result in deviation in free value reported and actual free memory**.

The integrated GPU on Tegra shares memory with CPU and other component of the SoC. The free and total values returned by the API excludes the SWAP memory space maintained by the OS on some platforms. The OS may move some of the memory pages into swap area as the GPU or CPU allocate or access memory. See Tegra app note on how to calculate total and free memory on Tegra.

For more accurate information of memory, just refer to cudaMemRangeGetAttribute, cudaMemAdvise. Those APIs will give detailed about how the program consume the memory.

**Comment by llv22** [comment]
@nagra00 Thanks quite a lot for your questions. I means for pytorch 2.0, the most important feature is to use trion for converting model into native effective one. However, people decide to drop supports for nvidia GPU with computation compatibility under 7.0 (I don't like it), [openai](https://github.com/openai/triton). Now I'm check if there are some hard restrictions for this, at least from code level. If not, migrating it to support 6.1 for my geoforce 1080 will be interesting. The remaining stuffs are just routine, little more than c++ code adjustment.

**Comment by nagra00** [comment]
Thank you for all the input regarding CUDA and memory. I will check in more detail. What makes me wonder is that no CUDA application is able to allocate more than about 8.9GB. I get the same results with a monitor connected to the GPU and a headless setup and that makes no sense to me…

Triton compiler for 6.1 cards would be indeed very cool. Lets wait and see if this is possible.

I have to thank you for all your work to make pytorch and other applications available for MacOS with CUDA !

**Comment by llv22** [comment]
@nagra00 yeah, let me know your results. I think 2.5G overheads on macOS doesn't make sense. also curious about why.
