### ISSUE TITLE
AttributeError: module 'pytorch_lightning.utilities.seed' has no attribute 'seed_everything'

### ISSUE THREAD

**Issue by MorAgiv** [llv22/pytorch-macOS-cuda#5]
### 🐛 Describe the bug

Hello,
This line: pl.utilities.seed.seed_everything(seed = hp.random_seed)
is giving this error:
AttributeError: module 'pytorch_lightning.utilities.seed' has no attribute 'seed_everything'
How to fix it? I already have the latest version of PyTorch  lightning (2.0.2)
Thank you!

**Comment by JokerOuO** [comment]
try pytorch_lightning.seed_everything

**Comment by llv22** [comment]
@JokerOuO as mentioned. but it's irrelevant with my project.
